title: "Akshay - Data Analytics Portfolio"
description: "A portfolio showcasing my data analytics projects."
remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-include-cache

author:
  name: "Akshay"
  linkedin: "https://www.linkedin.com/in/akshaysinha01"
  github: "https://github.com/AkshaySinha01"

# Navigation bar
nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "About"
    url: /about/

collections:
  projects:
    output: true
    permalink: /projects/:path/
  README:
    output: true
    permalink: /README/:path

# Navigation links
header_pages:
  - index.md
  - projects.md
  - README.md
